language: php

branches:
  only:
    - master

cache:
  directories:
  - vendor
  - venv

before_install: ./.travis/before_install.php
install: ./.travis/install.php
script: ./.travis/script.php
after_script: ./.travis/after_script.php

matrix:
  include:
    # old PHP versions with and without the Asset component (introduced in 2.7)
    - php: 5.3
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.3
      env: SYMFONY_VERSION=2.8.* # Symfony 3 doesn't support PHP 5.3
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    # HHVM with and without the Asset component (introduced in 2.7)
    - php: hhvm
      env: SYMFONY_VERSION=2.3.*
    - php: hhvm
      env: SYMFONY_VERSION=3.2.*
    # current PHP with all non-EOLed Symfony versions
    - php: 7.1
      env: SYMFONY_VERSION=2.3.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=dev-master
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
